export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const SET_TOPIC_SUBSCRIPTION_STATUS_BEGIN =
  'SET_TOPIC_SUBSCRIPTION_STATUS_BEGIN'
export const SET_TOPIC_SUBSCRIPTION_STATUS_SUCCESS =
  'SET_TOPIC_SUBSCRIPTION_STATUS_SUCCESS'
export const SET_TOPIC_SUBSCRIPTION_STATUS_ERROR =
  'SET_TOPIC_SUBSCRIPTION_STATUS_ERROR'
export const SET_ONBOARDING_MODAL_PREVIOUSLY_SHOWN =
  'SET_ONBOARDING_MODAL_PREVIOUSLY_SHOWN'
